### PR TITLE
Fixed nodes

### PR DESCRIPTION
**Pull request by iosonofabio**
Adding an option to fix some nodes into their initial communities as initially proposed in issue #7 . This change de facto extends the whole library to semi-supervised learning.

The current status of the PR is:
- NOT ready for merge
- interface at Python, CPython API, and C++ down to GraphHelper is there
- algorithmic logic for skipping the fixed nodes missing

I'll keep updating on this branch `fixed_nodes` on my github as I progress.

### CODE REVIEW

**Comment by iosonofabio** [comment]
Ok tests pass. I added a test for the fixed nodes and it seems fine. Could you have a look and tell me whether it looks good to you?
thanks!

**Comment by vtraag** [comment]
Thank you very much for all this work! It has been more work than I anticipated, and it is much appreciated that you have made that effort.

You have now taken the approach that the `fixed_nodes` are a property of `Graph`.  I can understand that approach, but I think it would make more sense to consider it as an argument to `Optimiser::optimise_partition`. Then the `fixed_nodes` need only be considered in that function, instead of as a separate argument in all partition types.

There are also a couple of issues that would need to be resolved before the implementation works correctly.
- The aggregation of the graph does not consider the fixed nodes. This is initialised to false by default, meaning that all aggregate nodes are free to move. In other words, the fixed nodes do not remain fixed after aggregation. See https://github.com/vtraag/leidenalg/blob/598c6121058143569e2880329ae0276414f5e0b5/src/GraphHelper.cpp#L812-L893
- Fixed nodes are still added to the queue in, meaning that they will be considered for moving at some point. See https://github.com/vtraag/leidenalg/blob/598c6121058143569e2880329ae0276414f5e0b5/src/Optimiser.cpp#L613-L626
- The communities are renumbered throughout the optimisation routine. See 
https://github.com/vtraag/leidenalg/blob/598c6121058143569e2880329ae0276414f5e0b5/src/Optimiser.cpp#L312
https://github.com/vtraag/leidenalg/blob/598c6121058143569e2880329ae0276414f5e0b5/src/Optimiser.cpp#L632
https://github.com/vtraag/leidenalg/blob/598c6121058143569e2880329ae0276414f5e0b5/src/Optimiser.cpp#L819
This of course destroys the idea that the membership of certain nodes are fixed.
- The input memberships are free to take any numerical input, but that should probably be restricted to the range 0,..., n - 1, because the aggregate graph (i.e. collapsed graph) will retain partly the initial number of communities, since the community membership of some nodes remains fixed. Otherwise, you can easily run into memory issues if a very large number is indicated as the initial membership for some node.

Given these type of intricacies, it may actually make sense to create a separate function `Optimiser::optimise_partition_fixed_nodes` and the associated necessary `move_nodes` and `merge_nodes` functions. Or perhaps it warrants even a completely separate `Optimiser` class, such as `Optimiser_Fixed` or something. Perhaps it is more convenient to discuss all this during a call at some point? Perhaps you can contact me by mail to setup a conference meeting?

**Comment by iosonofabio** [comment]
Hi Vincent,

Thanks for the thorough review. I'll write you to set up a time, I'm on the West Coast so that will be your late afternoon/my early morning.

Yes I was aware of the merging/renumbering issues, those need to be addressed but I thought I'd ask you for the line numbers ;-)

I took the approach of recycling community numbers in my own version of the library instead of forcing strict renumbering, but here that sounds like a bad idea. Renumbering the fixed input into 0..,n-1 and keeping a dictionary around for back-conversion at the end sounds more reasonable.

I took the GraphHelper approach because the optimise_partition (for both Python and C++) is minimalistic in terms of arguments (pretty much just the partition) whereas all the action (edge weights, node sizes, resolution parameter) is happening in the partition constructors. Moving all that stuff back out pretty much means restarting the PR from scratch, but like you say it may or may not be the best option. More via skype I'd say.

**Comment by iosonofabio** [comment]
#9 deprecates this PR, closing.

**Pull request closed without merging**
